server:
  port: 3000

spring:
  redis:
    host: localhost
    port: 6379

foursquare:
  host: https://foursquare.com
  api: https://api.foursquare.com/v2
  clientId: WQP3GYEKDDELPBTMTZAQ1VF04TKHJGPIMRWSFWBBHZT4MZEX
  clientSecret: D41DBYIKBQQYWBR5MTG2O1BQCSSKMSY2EQNHT52AA5OFLPUQ
  v: 20171001